# Configuration file for the warehouse environment
env_name: warehouse
seed: 42
max_steps: 200
terminate_on_trap: true

# Grid world settings
ascii_map: | # 7 x 13
  XXXXXXXXXXXXX 
  XH....1.....X 
  X..W..2.....X
  X..P..T..P..X
  X..3..D..4..X
  X.....W....5X
  XXXXXXXXXXXXX
# X = wall, .= empty, H = home, W = slide, P = portal
# T = trap, D = decoy, numbers = items to collect
# portal must be in pairs!!!

# Reward settings
c_step: -0.04
r_trap: -1.0
c_portal: -0.1
complete_bonus: 1.0
r_item: 0.5

# Stochasticity settings
p_stochastic: 0.3
decoy:
  p_stochastic: 0.1
  r_good: 0.8
  r_bad: -0.5